# Generated by Django 4.2.17 on 2025-01-05 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('contact_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='images')),
                ('content', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.blogger')),
            ],
        ),
    ]
